spring.application.name=MusouDB
# Agregar parametros para config la DB
spring.datasource.url=jdbc:mysql://localhost:3306/MusouDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=LuigiRdgz6533

# Config la accion de JPA
spring.jpa.hibernate.ddl-auto=update

# Config los logs de lo que hace JPA (fines educativos)
#   Esto no se ve en produccion
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true